export const routes = {
  HOME: "/",
  REGISTER: "/register",
  LOGIN: "/login",
  CATALOG_PAGE: "/catalog",
  PRODUCT_PAGE: "/product",
  CONFIRM_EMAIL: "/confirm-email",
  SUPPORT: "/support",
  ABOUT_US: "/about",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  SIZE_GUIDE: "/size-guide",
  FAVORITES: "/favorites",
  BASKET: "/basket",
  PROFILE: "/profile",
  MY_ORDERS: "/profile/my-orders",
  SUBMIT_ORDER: "/submit-order",
  ORDER_DETAILS: "/profile/my-orders",
  MOBILE_ORDER_DETAILS: "/profile-mobile",
  MOBILE_PROFILE: "/profile-mobile",
};
