export const routes = {
  HOME: "/",
  REGISTER: "/register",
  LOGIN: "/login",
  PROFILE: "/profile",
  CATALOG_PAGE: "/catalog",
  CONFIRM_EMAIL:"/confirm-email",
  LOGIN:"/login",
  PROFILE: "/profile",
  SUPPORT: "/support",
  ABOUT_US: "/about",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD:"/reset-password",
  TRACKING: "/tracking",
  SIZE_GUIDE: "/size-guide",
};
